-- Initial Supabase schema bootstrap for NanchuOps (trimmed scope).
-- Removed: salary_records, advance_records, chart_of_accounts, subcategories,
-- journal_entries, journal_entry_lines, purchases_records, expenses_records.

begin;

create extension if not exists pgcrypto;

create table if not exists public.branches (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  username text unique,
  email text unique,
  password text,
  role text not null default 'employee',
  full_name text,
  receives_transportation integer not null default 0,
  branch_id bigint references public.branches(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint users_role_check check (role in ('admin', 'branch_admin', 'employee', 'night_manager', 'rider_incharge'))
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  branch_id bigint references public.branches(id) on delete set null,
  name text not null,
  phone text,
  email text,
  permanent_address text,
  temporary_address text,
  receives_transportation integer not null default 0,
  salary numeric(10, 2) not null default 0,
  emergency_contact_name text,
  emergency_contact_number text,
  emergency_contact_relation text,
  bank_name text,
  bank_account_number text,
  joining_date text,
  post text,
  date_of_birth text,
  citizenship_number text,
  citizenship_issued_by text,
  citizenship_issued_date text,
  driving_license_number text,
  id_document_path text,
  driving_license_document_path text,
  in_payroll integer not null default 0,
  is_active integer not null default 1,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_records (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete restrict,
  branch_id bigint references public.branches(id) on delete set null,
  branch text,
  date text not null,
  amount numeric(15, 2) not null,
  total_amount numeric(15, 2),
  description text,
  category text,
  payment_method text,
  total_qr_sales numeric(15, 2) not null default 0,
  total_cash_sales numeric(15, 2) not null default 0,
  total_food_sales numeric(15, 2) not null default 0,
  total_beverages_sales numeric(15, 2) not null default 0,
  delivery_charge_collected numeric(15, 2) not null default 0,
  total_discount_given numeric(15, 2) not null default 0,
  total_rider_payment numeric(15, 2) not null default 0,
  transportation_amount numeric(15, 2) not null default 0,
  transportation_recipient_id bigint,
  transportation_recipients text,
  rider_payments text,
  other_expenses text,
  voucher_created integer not null default 0,
  record_number text,
  vat_type text,
  vat_rate numeric(5, 2) not null default 13.00,
  vat_amount numeric(15, 2) not null default 0,
  vat_calculation_method text,
  created_at timestamptz not null default now()
);

create index if not exists idx_employees_branch_id on public.employees (branch_id);
create index if not exists idx_users_branch_id on public.users (branch_id);
create index if not exists idx_sales_records_date on public.sales_records (date);
create index if not exists idx_sales_records_branch_id on public.sales_records (branch_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_branches_updated_at on public.branches;
create trigger trg_branches_updated_at
before update on public.branches
for each row execute function public.touch_updated_at();

insert into public.positions (name, description)
values ('Rider', 'Universal rider position')
on conflict (name) do nothing;

insert into public.branches (name, code, is_active)
values ('Main Branch', 'main', true)
on conflict (name) do nothing;

commit;
